targetConfigs:
- url: https://github.com/christianh814/fetchit-demo
  branch: main
  fileTransfer:
  - name: ft-ex
    targetPath: jj
    destinationDirectory: /tmp/christian
    schedule: "*/1 * * * *"
  raw:
  - name: raw-ex
    targetPath: containers
    schedule: "*/1 * * * *"
  kube:
  - name: kube-ex
    targetPath: kp
    schedule: "*/1 * * * *"
  branch: main
