configReload:
  schedule: "*/1 * * * *"
  configUrl: https://raw.githubusercontent.com/christianh814/fetchit-demo/main/config/config.yaml
targetConfigs:
- url: https://github.com/christianh814/fetchit-demo
  branch: main
  fileTransfer:
  - name: ft-ex
    targetPath: jj
    destinationDirectory: /tmp/christian
    schedule: "*/1 * * * *"
  raw:
  - name: raw-ex
    targetPath: containers
    schedule: "*/1 * * * *"
