apiVersion: v1
kind: Service
metadata:
  labels:
    app: welcome-php
  name: welcome-php
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 8080
  selector:
    app: welcome-php
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: welcome-php
  name: welcome-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      labels:
        app: welcome-php
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php:latest
        name: welcome-php
        resources: {}
